"""
Replicate the ADeLe/Nature paper's rWG methodology using the actual GPT-4o
annotations already present in our data:

  - The 'true' column in newset_merged_18rubrics.csv is the official ADeLe
    gold-reference level, generated by GPT-4o via the delean_batch_manager
    tool (default openai_model="gpt-4o"), on the 5 new external benchmarks.

Steps:
  1. rWG among the 4 models (Qwen, Llama-3.3, Mistral, Distilled) -- playing
     the role of "the 5 humans" in the paper.
  2. Consensus = median of the 4 models per item -- proxy for Delphi consensus.
  3. rWG(consensus, GPT-4o) -- directly comparable to the paper's
     rWG(Delphi consensus, GPT-4o) = 0.75-0.94, avg 0.86.
  4. Compare against the paper's reported values.
"""
import pandas as pd
import numpy as np

K = 6
SIGMA_EU2 = (K**2 - 1) / 12

df = pd.read_csv('newset_merged_18rubrics.csv')
MODELS = ['qwen', 'llama33', 'mistral', 'distilled']

def item_rwg(vals):
    vals = np.asarray(vals, dtype=float)
    var = vals.var(ddof=0)
    return 1 - var / SIGMA_EU2

RUBRIC_ORDER = ['AS','AT','CEc','CEe','CL','KNa','KNc','KNf','KNn','KNs',
                'MCr','MCt','MCu','MS','QLl','QLq','SNs','VO']

rows = []
for rubric in RUBRIC_ORDER:
    sub = df[df['rubric'] == rubric].copy()

    # Step 1: rWG among the 4 models
    rwg_4models = sub[MODELS].apply(item_rwg, axis=1).mean()

    # Step 2: consensus = median of the 4 models
    sub['consensus'] = sub[MODELS].median(axis=1)

    # Step 3: rWG(consensus, GPT-4o) -- GPT-4o = 'true' column
    pair = sub[['consensus', 'true']]
    rwg_vs_gpt4o = pair.apply(item_rwg, axis=1).mean()

    rows.append({
        'rubric': rubric,
        'n': len(sub),
        'rWG(Q,L,M,D)': round(rwg_4models, 3),
        'rWG(consensus, GPT-4o)': round(rwg_vs_gpt4o, 3),
    })

out = pd.DataFrame(rows)
out.to_csv('rwg_vs_gpt4o_final.csv', index=False)
print(out.to_string(index=False))
print()
print("=== Summary across 18 rubrics ===")
print(f"rWG among 4 models (Q,L,M,D):     mean={out['rWG(Q,L,M,D)'].mean():.3f}  range={out['rWG(Q,L,M,D)'].min():.3f}-{out['rWG(Q,L,M,D)'].max():.3f}")
print(f"rWG(consensus vs GPT-4o):         mean={out['rWG(consensus, GPT-4o)'].mean():.3f}  range={out['rWG(consensus, GPT-4o)'].min():.3f}-{out['rWG(consensus, GPT-4o)'].max():.3f}")
print()
print("=== Nature paper reference values ===")
print("rWG among 5 humans (pre-Delphi):  mean=0.83  range=0.70-0.91")
print("rWG(Delphi consensus vs GPT-4o):  mean=0.86  range=0.75-0.94")
